### ISSUE TITLE
Class 'app\models\AuditTrail' not found

### ISSUE THREAD

**Issue by icemall** [bedezign/yii2-audit#139] opened 2016-01-31 10:15 UTC
I've followed all the documentation steps, audit tables are being updated, but i get the error while trying to watch one of the model audit log: 

Class 'app\models\AuditTrail' not found

Even though behavior is attached.

What can be wrong in here, guys?

**Comment by Blizzke** [comment] 2016-01-31 11:32
It seems like you are trying to use the AuditTrail behavior without its namespace (it's `bedezign\yii2\audit\models\AuditTrail`). Unfortunately you are giving us very little information to continue with. A stack trace should be the very least here, we're not clairvoyants :)

**Comment by icemall** [comment] 2016-01-31 11:40
:)  I'm sorry 
I've put this in behaviors list of the model to audit, just like it says in documentation:
public function behaviors()
    {
        return [
            'bedezign\yii2\audit\AuditTrailBehavior'
        ];
    }
Model also contains getAuditTrails function. That's actually where it refers to the class it can't find. 
Module is also in config/Web modules section.

--
Отправлено из Mail.Ru для Android
воскресенье, 31 января 2016г., 14:32 +03:00 от Steve Guns <notifications@github.com>:

**Comment by Blizzke** [comment] 2016-01-31 11:51
Could you add the code for that `getAuditTrails`-function? 
I figure it can be fixed by either referring to the class as either `bedezign\yii2\audit\models\AuditTrail` or adding a `use bedezign\yii2\audit\models\AuditTrail;` statement at the top of your model.

**Comment by icemall** [comment] 2016-01-31 12:22
Sure, I took the code also from the documentation, here it is :
public function getAuditTrails()
    {
        return $this->hasMany(AuditTrail::className(), ['model_id' => 'id'])
            ->andOnCondition(['model' => get_class($this)]);
    }
--
воскресенье, 31 января 2016г., 14:51 +03:00 от Steve Guns <notifications@github.com>:

**Comment by Blizzke** [comment] 2016-01-31 12:30
As expected. Just add `use bedezign\yii2\audit\models\AuditTrail;` at top of the file, under the `namespace` statement. It's not a bug, since the AuditTrail there does not have a namespace PHP will look for it in the current namespace (being app\models in your case).

**Closed by Blizzke** 2016-01-31 12:30 UTC

**Comment by icemall** [comment] 2016-02-01 06:11
Thank you, Steve, you really helped me! 
--
Отправлено из Mail.Ru для Android
воскресенье, 31 января 2016г., 15:30 +03:00 от Steve Guns <notifications@github.com>:
